### ISSUE TITLE
Issue with property_exists

### ISSUE THREAD

**Issue by dereckson** [wolfplex/api-www#1]
Fatal error: Uncaught exception 'ErrorException' with message 'property_exists() expects parameter 2 to be string, object given' in /usr/home/dereckson/dev/wolfplex/api/api-www/pads/index.php:25 Stack trace: #0 [internal function]: {closure}(2, 'property_exists...', '/usr/home/derec...', 25, Array) #1 /usr/home/dereckson/dev/wolfplex/api/api-www/pads/index.php(25): property_exists('code', Object(stdClass)) #2 /usr/home/dereckson/dev/wolfplex/api/api-www/pads/index.php(42): get_pads() #3 {main} thrown in /usr/home/dereckson/dev/wolfplex/api/api-www/pads/index.php on line 25

**Comment by dereckson** [comment]
Fixed by b7b2620b355f953eda32e766ace0b16b3aab5021.
